[project]
name = "sapi-mcp"
version = "0.1.0"
description = "An example of using MCP to interact with the StationAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mcp[cli]>=1.8.1"]
